[package]
name = "teamsykmelding-pik-2"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.190"
serde_json = "1.0.108"
serde_derive = "1.0.183"
openssl = "0.10.59"
axum = "0.6.20"
tokio = { version = "1.34.0", features = ["full"] }
rdkafka = { version = "0.36.0", features = ["ssl"] }
uuid = { version = "1.5.0", features = ["v4", "serde"] }
log = "0.4.20"
log4rs = { version = "1.2.0", features = ["json_encoder"] }
time = "0.3.30"
prometheus = "0.13.3"
lazy_static = "1.4.0"

[dev-dependencies]
axum-test-helper = "0.3.0"
serde_yaml = "0.9.27"
