[package]
name = "teamsykmelding-pik-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
kafka = "0.9.0"
openssl = "0.10.40"
openssl-sys = "0.9.90"
