[package]
name = "teamsykmelding-pik-2"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.183"
serde_json = "1.0.104"
serde_derive = "1.0.183"
kafka = "0.9.0"
openssl = "0.10.56"
axum = "0.6.20"
tokio = { version = "1.29.1", features = ["full"] }