[package]
name = "teamsykmelding-pik-2"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.183"
serde_json = "1.0.104"
serde_derive = "1.0.183"
openssl = "0.10.56"
axum = "0.6.20"
tokio = { version = "1.30.0", features = ["full"] }
rdkafka = { version = "0.33.2", features = ["ssl"] }
uuid = { version = "1.4.1", features = ["v4", "serde"] }